language: rust
matrix:
  include:
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f407'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f417'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f427'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f429'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f437'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f439'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f469'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f479'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/rt nucleo-f429zi' ARGS="--release --target=thumbv7em-none-eabihf --example=pktgen"
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/rt nucleo-f429zi smoltcp-phy' ARGS="--release --target=thumbv7em-none-eabihf --example=ip"
script:
  - "cargo build --target=`uname -m`-unknown-linux-gnu --no-default-features --features \"$FEATURES\""
