language: rust
matrix:
  include:
    - rust: nightly
      env: FEATURES='stm32f407'
    - rust: nightly
      env: FEATURES='stm32f417'
    - rust: nightly
      env: FEATURES='stm32f427'
    - rust: nightly
      env: FEATURES='stm32f429'
    - rust: nightly
      env: FEATURES='stm32f437'
    - rust: nightly
      env: FEATURES='stm32f439'
    - rust: nightly
      env: FEATURES='stm32f469'
    - rust: nightly
      env: FEATURES='stm32f479'
    - rust: nightly
      env: FEATURES='stm32f429' ARGS="--release --target=thumbv7em-none-eabihf --example=pktgen"
    - rust: nightly
      env: FEATURES='stm32f429 smoltcp-phy smoltcp-log smoltcp-verbose' ARGS="--release --target=thumbv7em-none-eabihf --example=ip"
script:
  - "cargo build --target=`uname -m`-unknown-linux-gnu --no-default-features --features \"$FEATURES\""
