language: rust
matrix:
  include:
    - rust: nightly
      env: FEATURES='target-stm32f429'
    - rust: nightly
      env: FEATURES='target-stm32f7x9'
    - rust: nightly
      env: FEATURES='target-stm32f429' ARGS="--release --target=thumbv7em-none-eabihf --example=pktgen"
    - rust: nightly
      env: FEATURES='target-stm32f429 smoltcp-phy' ARGS="--release --target=thumbv7em-none-eabihf --example=ip"
script:
  - cargo build --no-default-features --features "$FEATURES"
