language: rust
matrix:
  include:
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f401'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f405'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f407'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f410'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f411'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f412'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f413'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f415'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f417'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f423'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f427'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f429'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f437'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f439'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f446'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f469'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/stm32f479'
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/rt stm32f4xx-hal/stm32f429' ARGS="--release --target=thumbv7em-none-eabihf --example=pktgen"
    - rust: nightly
      env: FEATURES='stm32f4xx-hal/rt stm32f4xx-hal/stm32f429 smoltcp-phy' ARGS="--release --target=thumbv7em-none-eabihf --example=ip"
script:
  - "cargo build --target=`uname -m`-`uname -p`-linux-gnu --no-default-features --features \"$FEATURES\""
