[package]
categories = ["embedded", "no-std"]
name = "nettest"
version = "0.0.0"

[dependencies]
cortex-m = "0.4.0"
cortex-m-semihosting = "0.2.0"
stm32f429x = { path = "../stm32f429x", features = ["rt"] }
alloc-cortex-m = "0.3.1"
volatile-register = "0.2.0"

[dependencies.cortex-m-rt]
features = ["abort-on-panic"]
version = "0.3.9"

[profile.release]
debug = true
lto = true
