[package]
categories = ["embedded", "no-std"]
name = "nettest"
version = "0.0.0"

[dependencies]
cortex-m = "0.4.3"
cortex-m-rt = { version = "0.3.12", features = ["abort-on-panic"] }
cortex-m-semihosting = "0.2.0"
stm32f429x = { path = "../stm32f429x", features = ["rt"] }
alloc-cortex-m = { git = "https://github.com/japaric/alloc-cortex-m.git" }
volatile-register = "0.2.0"

[profile.release]
debug = true
lto = true
