[package]
categories = ["embedded", "no-std", "hardware-support", "network-programming"]
name = "stm32-eth"
version = "0.0.0"
keywords = ["ethernet", "network", "st", "stm32", "stm32f4", "stm32f7", "eth", "ethernet", "driver"]

[dependencies]
cortex-m-semihosting = "0.2.0"
volatile-register = "0.2.0"
aligned = "0.1.1"

stm32f429 = { path = "../stm32f429", features = ["rt"], optional = true }

smoltcp = { git = "https://github.com/m-labs/smoltcp.git", default-features = false, features = ["proto-ipv4", "proto-ipv6", "socket-icmp", "socket-udp", "socket-tcp", "log", "verbose"], optional = true }
#smoltcp = { version = "0.4.0", default-features = false, features = ["alloc", "log", "verbose"], optional = true }
log = { version = "0.4.1", optional = true }

[features]
smoltcp-phy = ["smoltcp", "log"]
#default = []
default = ["target-stm32f429"]

# Targets
target-stm32f429 = ["stm32f429"]

[dev-dependencies]
cortex-m = "0.4.3"
cortex-m-rt = { version = "0.4.0" }
panic-itm = "0.1.0"

[[example]]
name = "pktgen"
required-features = ["target-stm32f429"]

[[example]]
name = "ip"
required-features = ["target-stm32f429", "smoltcp-phy"]

[profile.release]
debug = 2
lto = true
