[package]
categories = ["embedded", "no-std"]
name = "stm32f4x9-eth"
version = "0.0.0"
keywords = ["ethernet", "network", "stm", "stm32", "stm32f4", "stm32f7"]

[dependencies]
cortex-m = "0.4.3"
cortex-m-rt = { version = "0.3.12", features = ["abort-on-panic"] }
cortex-m-semihosting = "0.2.0"
stm32f429x = { path = "../stm32f429x", features = ["rt"], optional = true }
alloc-cortex-m = { git = "https://github.com/japaric/alloc-cortex-m.git" }
volatile-register = "0.2.0"

[features]
default = []

# Targets
board_stm32f429x = ["stm32f429x"]

[[example]]
name = "pktgen"
required-features = ["board_stm32f429x"]

[profile.release]
debug = 2
lto = true
